// <auto-generated />
namespace E_LearningApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class databaseOptimization3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(databaseOptimization3));
        
        string IMigrationMetadata.Id
        {
            get { return "202305100638399_databaseOptimization3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
